### ISSUE TITLE
Doc issue with cookbook/textfield_changes/ page

### ISSUE THREAD

**Issue by philburk** [Foso/Jetpack-Compose-Playground#107]
This code:

    Text("The textfield has this text: " + textState.value.text)

failed to compile with "Unresolved reference: text".
Removing the ".=text" worked:

    Text("The textfield has this text: " + textState.value)

**Comment by Foso** [comment]
Hi, thank you for reporting. Which Compose version are you using? I can find ".text"

https://github.com/Foso/Jetpack-Compose-Playground/blob/master/app/src/main/java/de/jensklingenberg/jetpackcomposeplayground/mysamples/github/material/textfield/TextFieldDemo.kt

**Comment by philburk** [comment]
Thanks for responding.

I installed Kotlin and Compose last week. I am excited about the multi-platform possibilities and appreciate your cookbook.

build.gradle has compose_version = "1.1.0-beta01.
kotlin version is 1.5.31
minSdk 29
targetSdk 32

The issue may be because I am trying to update plain text and not TextField text. This is one problem with duck typing. Sometimes type matters.

Here is the code snippet:
```
val mutableTextState = mutableStateOf("aardvark")

@Composable
fun ButtonWithColor(){
    val textState = remember { mutableTextState }
    Button(onClick = {
        textState.value = "clicked"
    },
    colors = ButtonDefaults.buttonColors(backgroundColor = Color.DarkGray))

    {
        Text("Status: " + textState.value.text)
    }
}
```

**Comment by Foso** [comment]
Hi, the difference in your code is that you are using the text directly and not a TextFieldValue(), .text is a property of it.

1.1.0-beta01 is a relative old version of Compose. I recommend that you update to the latest stable version (1.2.1) and Kotlin to 1.7.0. All code examples are also using 1.2.1

**Comment by philburk** [comment]
Thanks. That makes sense. Closing as WAI.
