### ISSUE TITLE
Path issue in doc

### ISSUE THREAD

**Issue by Holstie** [Foso/Jetpack-Compose-Playground#16]
mkdocs/index.md has wrong paths to the components individual page

**Replace with:**
* [ConstraintLayout](https://foso.github.io/Jetpack-Compose-Playground/layout/constraintlayout/)
* [Scaffold](https://foso.github.io/Jetpack-Compose-Playground/material/scaffold/)
* [Column](https://foso.github.io/Jetpack-Compose-Playground/layout/column/)
* [Row](https://foso.github.io/Jetpack-Compose-Playground/layout/row/)
* [Stack](https://foso.github.io/Jetpack-Compose-Playground/layout/stack/)
* [LayoutPadding](https://foso.github.io/Jetpack-Compose-Playground/core/layoutpadding/)

**Comment by Foso** [comment]
Hi @Holstie thank you for filing the issue. I fixed it :)
