### ISSUE TITLE
Is the documentation referring to an old version

### ISSUE THREAD

**Issue by z0xyz** [Foso/Jetpack-Compose-Playground#162]
I'm currently reading the documentation on the website. The problem is that some of the components i.e., `TopAppBar` have certain parameters that're not mentioned in other walkthroughs, namely `backgroundColor` and `elevation`.
The full code imports `Material`, and I'm using `Material3`, but when I've tried to import `Material` it only shows the `Icons` and `ripple` packages.
Even `MaterialTheme` has the class `colorScheme` not `colors`.
Am I missing something, or is the docs outdated?

**Comment by Foso** [comment]
the docs are referring to the current stable version of Compose (1.4.3) and it's not using Material3
