### ISSUE TITLE
Doc issue with foundation/text/ page

### ISSUE THREAD

**Issue by WarBorg** [Foso/Jetpack-Compose-Playground#28]
the latest Canary build (16) of Android Studio 4.2 with compose 1.0.0-alpha07 complains that Text in foundation is deprecated and androidx.compose.material.Text should be used or androidx.compose.foundation.text.BasicText if we don't want any specific theming. 

"Use androidx.compose.material.Text for a high level Text component that consumes theming information, or androidx.compose.foundation.text.BasicText for a basic unopinionated component that does not have default theming"

**Comment by Foso** [comment]
Thank you, I updated the text page
