### ISSUE TITLE
Please update the Compose binaries

### ISSUE THREAD

**Issue by natanfudge** [Foso/Jetpack-Compose-Playground#3]
11 hours ago [this commit](https://android.googlesource.com/platform/frameworks/support/+/443c300502c20b1ab0cc1a5788e5deb0331dd45b%5E1..443c300502c20b1ab0cc1a5788e5deb0331dd45b/) was added to AOSP that fixes [this critical issue](https://issuetracker.google.com/issues/133064200).  

P.S. I'm very grateful that you've been keeping the binaries up to date thus far.

**Comment by Foso** [comment]
Hi @natanfudge i updated the libraries
