### ISSUE TITLE
Doc issue with material/radiogroup/ page

### ISSUE THREAD

**Issue by jonneymendoza** [Foso/Jetpack-Compose-Playground#30]
At the tp of this function it has a object or variable called state that does not exist?

How is this "state" created? There is n reference to it at all

**Comment by Foso** [comment]
Hi @jonneymendoza , you are right. state doesn't exist anymore in the latest compose versions. I updated the sample to version 1.0.0-alpha07 and linked the source code at the bottom of the page

**Comment by jonneymendoza** [comment]
Ok thanks.

I guess you have taken down the page as i does not load for me anymore:

https://foso.github.io/Jetpack-Compose-Playground/material/radiogroup.md

**Comment by Foso** [comment]
https://foso.github.io/Jetpack-Compose-Playground/material/radiobutton/

**Comment by Foso** [comment]
@jonneymendoza I removed RadioGroup, because it was renamed to RadiobButton

**Comment by jonneymendoza** [comment]
Ok brilliant thanks. The sample now works perfectly
