### ISSUE TITLE
Doc issue with layout/constraintlayout/ page

### ISSUE THREAD

**Issue by ericntd** [Foso/Jetpack-Compose-Playground#32]
there's no method `tag()` under `ConstraintSet` scope
![Screen Shot 2020-12-03 at 11 38 44 AM](https://user-images.githubusercontent.com/19919208/101069866-95247f00-3568-11eb-9468-537be87d0681.png)

Using version 1.0.0-alpha08

**Comment by Foso** [comment]
Hi @ericntd , the page was very outdated. I updated it, with a simple but working example
