### ISSUE TITLE
Why not open the DemoActivity directly?

### ISSUE THREAD

**Issue by zqlq4ever** [Foso/Jetpack-Compose-Playground#65]
Why not open the DemoActivity directly but through MainActivity ? There are 2 startup icons on the desktop !
![130072793-1cdc6793-6579-4d2a-9ec8-e68d6b76e88f](https://user-images.githubusercontent.com/37474811/130166142-2b6b88f4-189a-4508-bdfb-1471d725dce5.png)
why not this :
![2](https://user-images.githubusercontent.com/37474811/130166161-951a0abd-f084-47f7-85a7-e7e4c0057701.png)

**Comment by Foso** [comment]
Hi, this because there once was a second module which could be started
