### ISSUE TITLE
bottom bar

### ISSUE THREAD

**Issue by elsadeny** [Foso/Jetpack-Compose-Playground#7]
Is there any example of a bottom navigation bar using jetpack compose? please let me know

**Comment by Foso** [comment]
Hi @elsadeny , yes, there are samples, take a look at https://github.com/Foso/Jetpack-Compose-Playground/blob/master/compose/src/main/java/de/jensklingenberg/jetpackcomposeplayground/ui/samples/androidx/ui/material/AppBarSamples.kt 

But I had problems loading the Image that the samples need, so i wrote a (ugly, but working) sample https://github.com/Foso/Jetpack-Compose-Playground/blob/master/compose/src/main/java/de/jensklingenberg/jetpackcomposeplayground/ui/samples/mysamples/material/BottomBar.kt

I hope this helps

**Comment by Foso** [comment]
I will close this issue, feel free to open a new one, if you have more questions :)
