### ISSUE TITLE
Doc issue with material/modaldrawer/ page

### ISSUE THREAD

**Issue by MtaufiqH** [Foso/Jetpack-Compose-Playground#72]
The [full Example code](https://github.com/Foso/Jetpack-Compose-Playground/blob/master/mysamples/src/main/java/de/jensklingenberg/jetpackcomposeplayground/mysamples/github/material/modaldrawer/ModalDrawerLayoutSample.kt) link is 404 Not Found respond. 
![image](https://user-images.githubusercontent.com/30973696/133394747-9eaf33e6-6047-4ad4-bdbe-9937f3e9cc52.png)

**Comment by Foso** [comment]
Thank you for reporting, i fixed it, it`s https://github.com/Foso/Jetpack-Compose-Playground/blob/master/mysamples/src/main/java/de/jensklingenberg/jetpackcomposeplayground/mysamples/github/material/modaldrawer/ModalDrawerSample.kt
