### ISSUE TITLE
Doc issue with material/topappbar/ page

### ISSUE THREAD

**Issue by tanmoy-sarkar-neu** [Foso/Jetpack-Compose-Playground#73]
Topbar doesn't have a title property.
![image](https://user-images.githubusercontent.com/59992141/134007990-90eeaacb-7762-46c5-9826-6d94e95a4f9c.png)

**Comment by Foso** [comment]
Hi, there is a title property https://developer.android.com/reference/kotlin/androidx/compose/material/package-summary#TopAppBar(kotlin.Function0,androidx.compose.ui.Modifier,kotlin.Function0,kotlin.Function1,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.unit.Dp)
