### ISSUE TITLE
No sample for input text

### ISSUE THREAD

**Issue by ranjeetsinha13** [Foso/Jetpack-Compose-Playground#8]
Please add sample for input Text `TextField` as well.

**Comment by Foso** [comment]
Hi @ranjeetsinha13 , i've added a TextFieldSampleDemo. (https://github.com/Foso/Jetpack-Compose-Playground/blob/5bc2b0446ea02bdd100e0cbccddc06c28e570b72/compose/src/main/java/de/jensklingenberg/jetpackcomposeplayground/ui/samples/androidx/ui/framework/TextFieldSample.kt) 

It's the last entry in the MainMenu. The fields have a white background, so you need to click below the labels, to select them

**Comment by alizx** [comment]
Fist link uses `State` which is deprecated now.
the second link is broken.
